CREATE TABLE IF NOT EXISTS ICON (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(200),
    LOCATION VARCHAR(200) NOT NULL UNIQUE,

    PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS USER (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(256) UNIQUE,
    BIO VARCHAR(200),
    PASSWORD VARCHAR(256) NOT NULL,
    ACCOUNT_TYPE INT NOT NULL DEFAULT 0,
    ICON INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (ID),
    FOREIGN KEY (ICON) REFERENCES ICON(ID)
);
CREATE TABLE IF NOT EXISTS ITEM_CATEGORY (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    COLOR VARCHAR(32) NOT NULL,

    PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS ITEM (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    CALORIES INT NOT NULL,
    PROTEIN INT NOT NULL,
    CARBS INT NOT NULL,
    FAT INT NOT NULL,
    COST INT,
    SERVING_SIZE VARCHAR(50) NOT NULL,
    ICON INT NOT NULL DEFAULT 1,
    CATEGORY INT NOT NULL,
    CREATED_BY INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (ID),
    FOREIGN KEY (ICON) REFERENCES ICON(ID),
    FOREIGN KEY (CATEGORY) REFERENCES ITEM_CATEGORY(ID),
    FOREIGN KEY (CREATED_BY) REFERENCES USER(ID)
);
CREATE TABLE IF NOT EXISTS MEAL (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200),
    USER INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),

    PRIMARY KEY (ID),
    FOREIGN KEY (USER) REFERENCES USER(ID)
);
CREATE TABLE IF NOT EXISTS MEAL_ITEM (
    ID INT NOT NULL AUTO_INCREMENT,
    ITEM INT NOT NULL,
    MEAL INT NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (ITEM) REFERENCES ITEM(ID),
    FOREIGN KEY (MEAL) REFERENCES MEAL(ID)
);